export enum AppEvents {
  // == products == //
  GET_PRODUCTS_FETCH = "GET_PRODUCTS_FETCH",
  GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS",
  GET_PRODUCTS_ERROR = "GET_PRODUCTS_ERROR",

  // == names == //
  GET_NAMES_FETCH = "GET_NAMES_FETCH",
  GET_NAMES_SUCCESS = "GET_NAMES_SUCCESS",
  GET_NAMES_ERROR = "GET_NAMES_ERROR",

  // == cart == //
  CHANGE_CART = "CHANGE_CART",
  UPDATE_USD = "UPDATE_USD"
}